// generated by joiner -- DO NOT EDIT
package main

import (
	"fmt"
	"strings"
)

func (t MyData) String() string {
	return fmt.Sprintf("%#v", t)
}

type JoinMyData []MyData

func (j JoinMyData) With(sep string) string {
	all := make([]string, 0, len(j))
	for _, s := range j {
		all = append(all, s.String())
	}
	return strings.Join(all, sep)
}
